import ee
from sepal_ui.scripts import utils as su


@su.need_ee
def compute_driver_index(aoi_model, model):
    """
    example function to load a gee based map
    """

    # as an example we laod the CAFI fragmentation map generated by Peter Vogt and I
    frag = ee.Image("projects/cafi_fao_congo/classification/fragmentation_2015")
    fragcaf = frag.select("b1").clip(aoi_model.feature_collection)
    zonesfragcaf = (
        fragcaf.gt(1)
        .add(fragcaf.gt(2))
        .add(fragcaf.gt(3))
        .add(fragcaf.gt(4))
        .add(fragcaf.gt(5))
        .add(fragcaf.gt(6))
    )
    zonesfragcaf = zonesfragcaf.updateMask(zonesfragcaf.neq(0))

    return zonesfragcaf
